### ISSUE TITLE
Minor issues when working with Heroku

### ISSUE THREAD

**Issue by ghost** [saasbook/hw-rails-intro#1]
Hi, I'm reviewing the online material and doing this homework (thanks for releasing such a terrific course!). So far, my development environment runs nicely but, unfortunately, I ran into some issues when trying to deploy to Heroku:
- The Gemfile specifies that HAML will only be installed in development and test environments, so the views are not been rendered (ActionView::MissingTemplate error). Besides, I had to move the sqlite gem to development and test groups in order to deploy to Heroku.
- The movie model uses attr_accesible which is not supported in Rails 4. Apparently, this wasn't a problem for my local environment but, on Heroku, I had to use [strong parameters](http://easyactiverecord.com/blog/2014/04/01/rails4-strong-parameters-and-the-attr-accessible-macro/) instead.

**Comment by siddhantpuri** [comment]
Hi

Can you send us the error message you're receiving maybe some screenshots.
In the production environment file there should be that lets you treats all
requests as local requests and it will give you a more useful error message

Sent from my iPhone

On Jul 25, 2015, at 9:39 AM, Ernesto Rosas notifications@github.com wrote:

Hi, I'm reviewing the online material and doing this homework (thanks for
releasing such a terrific course!). So far, my development environment runs
nicely but, unfortunately, I ran into some issues when trying to deploy to
Heroku:

   -

   The Gemfile specifies that HAML will only be installed in development
   and test environments, so the views are not been rendered
   (ActionView::MissingTemplate error). Besides, I had to move the sqlite gem
   to development and test groups in order to deploy to Heroku.
   -

   The movie model uses attr_accesible which is not supported in Rails 4.
   Apparently, this wasn't a problem for my local environment but, on Heroku,
   I had to use strong parameters
   http://easyactiverecord.com/blog/2014/04/01/rails4-strong-parameters-and-the-attr-accessible-macro/
   instead.

—
Reply to this email directly or view it on GitHub
https://github.com/saasbook/hw-rails-intro/issues/1.

**Comment by ghost** [comment]
BTW, I´ve already modified some files and my app is up and running on Heroku.

##### **Heroku complaining about sqlite gem:**

![cap1](https://cloud.githubusercontent.com/assets/8901389/8891174/8cc8cf0a-32e4-11e5-9d96-06c9f5eb7bed.jpg)

##### **Issue with attr_accesible method:**

![cap2](https://cloud.githubusercontent.com/assets/8901389/8891183/e32fe572-32e4-11e5-9910-7689005f418a.jpg)

##### **ActionView template error:**

![cap3](https://cloud.githubusercontent.com/assets/8901389/8891246/af4f81f6-32e7-11e5-847f-8e8539199d08.jpg)

**Comment by armandofox** [comment]
yes, the updated hw should use the strong parameters mechanism exclusively, since attr_accessible and attr_protected are gone from rails 4.

and yes, haml should be in all envs, and sqlite3 should NOT appear in production (whereas pg should appear).

sid - how was this not caught in testing?  i assume that testing for the deployable hw's includes deploying to heroku...or is the problem that he's not using the latest version?  (ernesto - we're upgrading all the hw's to be rails 4 compatible but we haven't released all the updated ones yet...)

Armando Fox
Professor, Computer Science Division
Faculty Advisor, UC Berkeley MOOCLab
fox .at. cs .dot. berkeley .dot. edu
581 Soda Hall MC#1776, Berkeley, CA 94720-1776
+1.510.642.6820 / http://www.cs.berkeley.edu/~fox

TAKE MY CLASS FOR FREE VIA edX:  http://saas-class.org  
LIKE IT ON FACEBOOK:  http://facebook.com/saas-class
TRY MY BOOK (NOT FREE): http://beta.saasbook.info (goes with the course)
